### ISSUE TITLE
Cannot run the built image on a PICO-IMX8MQ

### ISSUE THREAD

**Issue by alizeaga** [TechNexion-customization/ubuntu-tn-imx#1]
Hi,
I'm trying to run this Ubuntu 20.04 LTS on a PICO-IMX8M**Q** but for some reason it doesn't work. I compile and build it for the PICO-IMX8M generic platform, since there is no option for the specific PICO-IMX8M**Q** platform.
However, the precompiled image of Ubuntu 20.04 downloaded from the Technexion's FTP servers (and specifically tagged as PICO-IMX8M**Q**) works fine in my SoM.
Am I missing something or does this repository really not work for the PICO-IMX8M**Q** platform?
Any help will be most appreciated.
Best regards!

**Comment by wigcheng** [comment]
What is your Ubuntu revision on host PC? it's better if your provide compile error messages.

**Comment by alizeaga** [comment]
Thanks for your help. Finally I realized, I missed this error:
"E: Cannot install into target '/media/aitor/aitor/ubuntu-tn-imx/rootfs' mounted with noexec or nodev".
I'm using an external disc, so I remounted it with exec and dev options and then everything worked perfectly.
BTW, I'm using Ubuntu 20.04 LTS on my host PC.

**Comment by wigcheng** [comment]
Good news, Ubuntu 20.04 should be works perfectly.
I close this ticket, thanks!
