### ISSUE TITLE
How to build BLE  and WIFI by standalone

### ISSUE THREAD

**Issue by sintian** [TechNexion-customization/ubuntu-tn-imx#12]
Hello
Because my original system was built with standalone, if I want to use standalone to build BLE and WIFI again, can you please suggest me how to choose from make menuconfig?
Model: TechNexion PICO-IMX6 DualLite/Solo
Board: pico-imx6
OS：Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-142-generic x86_64)
Thanks!

**Comment by wigcheng** [comment]
I don't understand your question, Only WiFi need driver and it's out-of-tree driver, and this repo already include this driver inside the image using make all command, so I don't know what you need, thanks a lot

**Comment by sintian** [comment]
Ok, I understand. Thanks for your reply.
Best regards!

**Comment by sintian** [comment]
Hi @wigcheng 
Can you please tell me where I should ask questions about this page (e.g. Kernel Modules)?
https://developer.technexion.com/docs/how-to-rebuild-and-install-the-kernel-and-kernel-modules-on-ubuntu#
Thanks!

**Comment by wigcheng** [comment]
Also here :)
What is the problem there?

**Comment by sintian** [comment]
Hi @wigcheng :
That's great! I have some questions!

Since I made different modules (Pico-IMX6 /Ubuntu 16.04) according to the steps of the webpage there, but later I needed WIFI and BLE functions.
Can you please tell me how do I include the required driver in the step of configuring the kernel module (make menuconfig)?
Thanks!

**Comment by wigcheng** [comment]
I assuming your question is: you want to compile kernel with qca9377 driver by yourself.

Basically,  Only Wifi need dirver as I said before, Bluetooth only make sure UART function is working, and use bluez tool to control it.

And about Wifi driver compiling, you can refer this repo and step by step to compile it, should be works.

https://github.com/TechNexion/qcacld-2.0

Good luck :)

**Comment by sintian** [comment]
Ok, I will try it! Thanks for your reply ^_^

**Comment by sintian** [comment]
Hi @wigcheng :
Unfortunately I haven't succeeded yet and still need your help.
I downloaded the qcacld-2.0 folder to the linux directory, and followed the repo and the steps are as follows:
$KERNEL_SRC=/home/linux CONFIG_CLD_HL_SDIO_CORE=y CONFIG_PER_VDEV_TX_DESC_POOL=1 SAP_AUTH_OFFLOAD=1 CONFIG_QCA_LL_TX_FLOW_CT=1 CONFIG_WLAN_FEATURE_FILS=y CONFIG_FEATURE_COEX_PTA_CONFIG_ENABLE=y CONFIG_QCA_SUPPORT_TXRX_DRIVER_TCP_DEL_ACK=y CONFIG_WLAN_WAPI_MODE_11AC_DISABLE=y TARGET_BUILD_VARIANT=user  CONFIG_NON_QC_PLATFORM=y CONFIG_HDD_WLAN_WAIT_TIME=10000 make -j6
$KERNEL_SRC=/home/linux INSTALL_MOD_PATH=./modules_wifi make modules_install

Then there are zImage and some .ko files generated, and the 4.1.15_2.0.0-g06465e7-dirty folder under /lib/modules.
I tried to put zImage and 4.1.15_2.0.0-g06465e7-dirty into i.MX6, and put the WIFE firmware into /lib/firmware, but the wifi still failed. Am I missing something, or which ko file is insmod needed?
Thanks!

**Comment by wigcheng** [comment]
Why you change back to kernel 4.1?
Note that the support list on qcacld README file of repo:
Support kernel: 4.9.x 4.14.x 5.4.x 5.10.x

Second, module_install need assign your kernel modules prebuilt path, not ./ path, it will install to your qcacld path, that strange.

Thanks

**Comment by sintian** [comment]
Hi @wigcheng 
Thank you for reminding that the kernel version is ignored. As mentioned earlier, it is the product made by referring to the URL step before, and the webpage has the label Kernel Branch: tn-imx_4.1.15_2.0.0_ga.
Because the stability of the system has been verified, I don't want to change too much. Therefore, I originally preferred to continue to use make menuconfig to try. Do you have any suggestions or other methods?
Any news is greatly appreciated.

**Comment by wigcheng** [comment]
If you adapt kernel 4.1.15 for your target platform, you might be port yourself using qcacld driver because we're not support that, or you can send mail to sales@technexion.com to discuss customize service.

Just wonder why you can use kernel 4.1.15, so your PICO-IMX6 should be base on earlier WIFI module, not QCA module.

**Comment by sintian** [comment]
Ok, Thanks for your reply!
Best regards.
