### ISSUE TITLE
Dual Display question

### ISSUE THREAD

**Issue by LeoChang88** [TechNexion-customization/ubuntu-tn-imx#14]
Hello,
I have tried to port a LVDS panel to the edm-g-imx8mp board, and it works,
but the HDMI+LVDS are "expand mode", how can I change them to "clone mode"?

thanks.

**Comment by wigcheng** [comment]
We'll fix it on next Ubuntu Gnome image, you can test pre-release image as follows link:
https://download.technexion.com/demo_software/EDM-G/IMX8/edm-g-imx8mp/DiskImage/edm-g-imx8mp_edm-g-wb_ubuntu-20.04-gnome_qca9377_pre-release_20211215.zip

**Comment by LeoChang88** [comment]
We can not test it due to our LVDS panel not defined in the device tree, 
When will you release the source code for Ubuntu Gnome image? thanks.

**Comment by wigcheng** [comment]
Ubuntu Gnome is base on Yocto 3.3 and it's already in our github now.
https://github.com/TechNexion/tn-imx-yocto-manifest/tree/hardknott_5.10.y-next#for-edm-g-imx8mp

I have a question, I remember you adapt Android 11 first, why change to Ubuntu? Because Android 11 default dual display is 'clone' mode, and it also support dual mode using an app inside the image, should be easier for you.

Thanks

**Comment by LeoChang88** [comment]
Because Ubuntu is our first priority , and we also want to support Android in the future, so we just test it and report the issue occurred during our image building & testing.

**Comment by wigcheng** [comment]
Got it, you can use ubuntu gnome image, then change kernel image and dtb files using yours directly, should be works as well.

But Ubuntu Gnome is base on kernel 5.10.72, you might be move your commits to that branch if your current kernel boot failed.

**Comment by LeoChang88** [comment]
Maybe we will try to build Ubuntu Gnome image first, still thank for your helping.

**Comment by LeoChang88** [comment]
@wigcheng I have a issue in the process of image building and no one responds me:
[https://github.com/TechNexion/tn-imx-yocto-manifest/issues/25](url)

**Comment by wigcheng** [comment]
I cannot see issue 25, very strange, maybe github issue?
Could you post again? Thanks a lot

**Comment by LeoChang88** [comment]
https://github.com/TechNexion/tn-imx-yocto-manifest/issues
Could you see my issue here?
