### ISSUE TITLE
"resulting binary is not-functional" warning - expected? OK?

### ISSUE THREAD

**Issue by mrpathos** [TechNexion-customization/ubuntu-tn-imx#17]
Apologies in advance; My background is largely application and videogame programming and we're still a skeleton crew so I'm diving into getting our WB-EDM-G-IMX8MP dev board up and running.

When I pull this repo, checkout v20.04-lts-03, and just dive straight into "make all PLATFORM=edm-g-imx8mp", it largely seems to work right out of the box (impressive!) But then the image doesn't actually work on the wandboard.

I note that in the u-boot build step it complains that lpddr4_pmu_train_1d_imem.bin and friends aren't found and "resulting binary is not-functional".

But I see that install_uboot_imx8.sh - which requires u-boot be built before it runs - downloads those very files and then does some... stuff, with them.

Is this warning expected? Is the install_uboot_imx8.sh script stuffing those files in the right place after the fact and theoretically making the image functional? (If so, then I'm confused why the image doesn't boot when I push it to eMMC.)

Or is this warning not supposed to happen, and am I missing some step where I'm supposed to pull those files down myself manually ahead of time? And where would I pull them to, since the build process for ubuntu-tn-imx itself clones the u-boot-tn-imx repo into a cache dir?

Thanks so much for any help! I promise my questions will get less basic over time, if not fewer in number.

**Comment by mrpathos** [comment]
So I ran the build once and let it fail (or warn about a not-functional binary), then I manually copied the lpddr* files directly into the output/u-boot/u-boot-tn-imx dir, using the _202006 versions (and copying those files to the non-_202006 filename versions too just in case), as it appears those are the ones for the imx8m. Built with `make all PLATFORM="edm-g-imx8mp"` from the root ubuntu-tn-imx and this time it completed and output a ubuntu.img with no serious warnings at all. uuu'd it to the wandboard eMMC and it doesn't boot at all, just goes straight into serial download mode.

When it doesn't boot, like this, I note that I also get no information off the serial debug port, either - when I boot one of the demo images I get all sorts of output to my terminal emulator, so I have the settings right, but on a bad binary it just gives me zero bytes and goes into serial download mode, so I'm not super sure how to go about debugging this.

Would you expect that the following steps:

git clone <ubuntu-tn-imx>
cd ubuntu-tn-imx
git checkout v20.04-lts-03
make all PLATFORM="edm-g-imx8mp"

and then taking the resulting ubuntu.img and uuu'ing it to the WB-EDM-G-IMX8MP eMMC and rebooting the wandboard...

... should succeed? If not, any way to point me in the direction of what I'm missing, here?

Thank you!!

**Comment by wigcheng** [comment]
@mrpathos 

Just tried the steps as you mention:
git clone
cd ubuntu-tn-imx
git checkout v20.04-lts-03
make all PLATFORM="edm-g-imx8mp"

And I can boot up success into Weston desktop, should be no problems ( first boot will expand partition size then reboot once, detail can following Technexion developer wiki)

So I think the root cause is you change u-boot DDR firmware manually, you can separated the compile steps to focus on u-boot only:

make u-boot PLATFORM="edm-g-imx8mp"

Should be no need change DDR firmware manually, maybe you missing some prebuilt packages on host PC side, also double check again if possible:

https://github.com/TechNexion-customization/ubuntu-tn-imx/blob/master/README-imx8.md#compiling-environment-setup


Thanks

**Comment by mrpathos** [comment]
When you do the above, do you get a warning early in the build (during u-boot build) that says:

`WARNING: 'lpddr4_pmu_train_1d_imem.bin' not found, resulting binary is not-functional`?

If you don't, then I am very confused. If you do, and your binary works, then that means the install_uboot_imx8.sh script is indeed doing something to put that bin file in the right spot to make it function.

I did the exact steps you list above from a completely fresh pull of the repo and the binary didn't work. I was building on Ubuntu 20.04 but it was in WSL2. I'm trying again right now on an actual bare metal Ubuntu install on a different machine in case WSL2 is the problem.

**Comment by mrpathos** [comment]
*sigh* - yeah, so for whatever reason, building with WSL2 generates a non-bootable image - building on bare Ubuntu worked fine. It does still yield that "resulting binary will be not-functional" warning during u-boot compile, which I wasted too much time chasing down. I guess that's not the problem and a later step injects the firmware files to the right place.

Thanks for the help, sorry it turned out to just be WSL2!
