### ISSUE TITLE
IMX8MM PICO PI

### ISSUE THREAD

**Issue by zhanlinux** [TechNexion-customization/ubuntu-tn-imx#18]
Hello! Why is there no more support for imx8mm?

Best regards

**Comment by wigcheng** [comment]
Did you mean for Ubuntu 22.04? Because ARM64 platform already move to Yocto based Ubuntu Gnome 20.04:

https://github.com/TechNexion/tn-imx-yocto-manifest#for-edm-g-imx8mp

Then change to pico-imx8mm, it should works.

About Ubuntu Gnome 22.04, should be released on Q3.
