### ISSUE TITLE
Issue to load image

### ISSUE THREAD

**Issue by cherifseye** [TechNexion-customization/ubuntu-tn-imx#20]
Hello, I'm facing some issues to load image in my Hard, I use an SD Card and galena Fetcher to flash the image. but when I'm trying to boot in my TEP it's not working.

My hardware: TEP0700IMX6G05R05
imx6ul-tep1.dtb

Thanks,

Cherif

**Comment by Bruce-Hung** [comment]
Hi Cherif,

How are you! This is Bruce , PM from Technexion.
We got your message and will try best to solve your problem.

We understand the product is TEP0700IMX6G05R05
TEP 7 INCH PCAP TOUCH LCD PC NXP I.MX6UL + 512MB RAM + 4G EMMC WITH 12V INPUT
drivertree:imx6ul-tep1.dtb
During to make sure the problem in detail. we need your help to provide us some enhance information:

Could you please let us know the follow information:
(1) When do you buy this product ( Shipping date?)
(2) How do your download the ubuntu image from FTP or Github?
(3) please help to check the Product serial number?

Thanks for your help.

Bruce

**Comment by cherifseye** [comment]
Hi, Bruce,

Thanks for your reply,

(1) We ordered the product for November 2021, and we got it.

(2) I download the image from GitHub

(3) Serial ID:17202112100021480001

Thank you,

Cherif

**Comment by Bruce-Hung** [comment]
Hi Cherif,


Thanks for your quickly response.
I am sorry may I make sure again your download is the image of tep0700 imx7 ?
We just want to make sure your download path is correct . ( GitHub)
Please kindly help to check the above again.

Thanks for your help!

Bruce

**Comment by cherifseye** [comment]
Hi  Bruce,

I use the image wich is in this repo [(https://github.com/TechNexion-customization/ubuntu-tn-imx/blob/master/README-imx6.md)

Thanks

**Comment by Bruce-Hung** [comment]
Hi Cherif


Thanks for your reply. we got it.
Please try to download the preview image as the follow link:

https://download.technexion.com/demo_software/TEP/IMX6/tep0700-imx6ul/DiskImage/
tep1-imx6ul_ubuntu-16.04_sdcard-preview_TTL_LCD-800x480_20170823.img

Thanks,

Bruce

**Comment by cherifseye** [comment]
Hi Bruce,

Thanks so much for help, really appreciated it
