### ISSUE TITLE
Flashing the image to the target board

### ISSUE THREAD

**Issue by DalitsoOttorino** [TechNexion-customization/ubuntu-tn-imx#3]
Hi Wigcheng,

I have another question:

I am trying to flash the pico-pi-imx7d board using uuu as my u-boot is not working so I cannot use ums.

In the readme:
`$ sudo uuu/linux64/uuu -b emmc_img imx6/pico-imx6-flash.bin ubuntu.img`

I would like to confirm [imx6/pico-imx6-flash.bin] in my case would be the u-boot.bin I build?
~/ubuntu-tn-imx/output/u-boot/u-boot-tn-imx/u-boot.bin

I'm not sure where is emmc_img, can you share your emmc_img with us?

Thanks. Happy Chinese New Year!

**Comment by DalitsoOttorino** [comment]
Update:

I followed these guides:
1. https://developer.technexion.com/mediawiki/Building-from-source-ubuntu-vm
2. https://github.com/TechNexion/u-boot-tn-imx/wiki/Use-mfgtool-%22uuu%22-to-flash-eMMC

I realized emmc_img is a script in uuu.

I am currently running the command:
 `$ sudo ./imx-mfgtools-tn/uuu/uuu -b emmc_imx7_img ~/ubuntu-tn-imx/output/u-boot/u-boot-tn-imx/SPL ~/ubuntu-tn-imx/output/u-boot/u-boot-tn-imx/u-boot.img ~/ubuntu-tn-imx/output/ubuntu.img`

However, it is not working either. It is running but it keeps on looping in 1:1. From 1/3 100%, to 2/3 100%, finally 3/3 100%, but after this goes back to 1/3.

Output from debug terminal is as follow:
```
Welcome to minicom 2.7.1

OPTIONS: I18n 
Compiled on Dec 23 2019, 02:06:26.
Port /dev/ttyUSB0, 12:25:48

Press CTRL-A Z for help on special keys

Downloading file of size 561576 to 0x877fffc0... done
Jumping to header at 0x87800000
Header Tag is not an IMX image
Found header at 0x87800000

U-Boot 2018.03 (Feb 16 2021 - 12:10:38 +0800)

CPU:   Freescale i.MX7D rev1.2 1000 MHz (running at 792 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 36C
Reset cause: POR
Board: PICO-IMX7D
Compatible baseboard: dwarf, hobbit, nymph, pi
I2C:   ready
DRAM:  1 GiB
PMIC: PFUZE3000 DEV_ID=0x30 REV_ID=0x11
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Failed (-5)

U-Boot SPL 2018.03 (Feb 16 2021 - 12:10:38 +0800)
Trying to boot from USB SDP
SDP: initialize...
SDP: handle requests...
Downloading file of size 561576 to 0x877fffc0... done
Jumping to header at 0x87800000
Header Tag is not an IMX image
�ound header at 0x87800000

U-Boot 2018.03 (Feb 16 2021 - 12:10:38 +0800)

CPU:   Freescale i.MX7D rev1.2 1000 MHz (running at 792 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 36C
Reset cause: POR
Board: PICO-IMX7D
Compatible baseboard: dwarf, hobbit, nymph, pi
I2C:   ready
DRAM:  1 GiB
PMIC: PFUZE3000 DEV_ID=0x30 REV_ID=0x11
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Failed (-5)
D
U-Boot SPL 2018.03 (Feb 16 2021 - 12:10:38 +0800)
Trying to boot from USB SDP
SDP: initialize...
SDP: handle requests...
Downloading file of size 561576 to 0x877fffc0... done
Jumping to header at 0x87800000
Header Tag is not an IMX image
�ound header at 0x87800000

U-Boot 2018.03 (Feb 16 2021 - 12:10:38 +0800)

CPU:   Freescale i.MX7D rev1.2 1000 MHz (running at 792 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 36C
Reset cause: POR
Board: PICO-IMX7D
Compatible baseboard: dwarf, hobbit, nymph, pi
I2C:   ready
DRAM:  1 GiB
PMIC: PFUZE3000 DEV_ID=0x30 REV_ID=0x11
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Failed (-5)
D
U-Boot SPL 2018.03 (Feb 16 2021 - 12:10:38 +0800)
Trying to boot from USB SDP
SDP: initialize...
SDP: handle requests...
Downloading file of size 561576 to 0x877fffc0... done
Jumping to header at 0x87800000
Header Tag is not an IMX image
Found header at 0x87800000

U-Boot 2018.03 (Feb 16 2021 - 12:10:38 +0800)

CPU:   Freescale i.MX7D rev1.2 1000 MHz (running at 792 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 36C
Reset cause: POR
Board: PICO-IMX7D
Compatible baseboard: dwarf, hobbit, nymph, pi
I2C:   ready
DRAM:  1 GiB
PMIC: PFUZE3000 DEV_ID=0x30 REV_ID=0x11
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Failed (-5)
�
U-Boot SPL 2018.03 (Feb 16 2021 - 12:10:38 +0800)
Trying to boot from USB SDP
SDP: initialize...
SDP: handle requests...
Downloading file of size 561576 to 0x877fffc0... done
Jumping to header at 0x87800000
Header Tag is not an IMX image
�ound header at 0x87800000

U-Boot 2018.03 (Feb 16 2021 - 12:10:38 +0800)

CPU:   Freescale i.MX7D rev1.2 1000 MHz (running at 792 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 36C
Reset cause: POR
Board: PICO-IMX7D
Compatible baseboard: dwarf, hobbit, nymph, pi
I2C:   ready
DRAM:  1 GiB
PMIC: PFUZE3000 DEV_ID=0x30 REV_ID=0x11
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
Loading Environment from MMC... *** Warning - bad CRC, using default environment

Failed (-5)
�
U-Boot SPL 2018.03 (Feb 16 2021 - 12:10:38 +0800)
Trying to boot from USB SDP
SDP: initialize...
SDP: handle requests...
```

I tried to use another USB-type A to USB-type C cable but it still have the same issue. Can you help me on the problem?

**Comment by wigcheng** [comment]
It seems your power supplier is not stable from USB port of PC, change other ports and try again (maybe remove panel first).
Another way is provide a external power using 40-pin PIN header on PI baseboard just like raspberry pi, but I recommend you need to know what you do before do this way, because it has risk to burn the hardware.....

**Comment by wigcheng** [comment]
You also can try ums way on u-boot, it's easier!

**Comment by DalitsoOttorino** [comment]
Hi Wigcheng,

You're awesome! I appreciate your help a lot. It is indeed power issue. It is flashed.
What I did was to connect an external 5V supply to J8; pin 4 is 5V and pin 6 is ground.

However, when I reboot, it didn't start up. U-boot is not loaded at all. Serial comm and terminal both does not output anything.

I noticed I could interact with U-boot right after flashing, so before I reboot the system, I do `=> ums 0 mmc 0` to inpect what has been flashed.

This is the drive: 
![Screenshot from 2021-02-18 19-46-56](https://user-images.githubusercontent.com/46814845/108502090-36f87400-72ed-11eb-93db-b5f20f08087d.png)
Each partition:
![Screenshot from 2021-02-18 19-47-08](https://user-images.githubusercontent.com/46814845/108502183-598a8d00-72ed-11eb-9dff-b5f94ec238a8.png)
![Screenshot from 2021-02-18 19-47-19](https://user-images.githubusercontent.com/46814845/108502189-5c857d80-72ed-11eb-9477-29b79c3d8afe.png)
Content in each partition:
![Screenshot from 2021-02-18 19-47-45](https://user-images.githubusercontent.com/46814845/108502226-70c97a80-72ed-11eb-99d4-a56ac20d86e1.png)
![Screenshot from 2021-02-18 19-47-50](https://user-images.githubusercontent.com/46814845/108502230-72933e00-72ed-11eb-891e-80e0db689056.png)

I suspect U-boot isn't flashed properly, so I tried a few more times but still to no avail.

So I went back to building the u-boot, kernel, rootfs and ubuntu.img again. I discovered, it didn't build properly. After changing setting: Download source code from main server, I encountered error when building rootfs again.

**Comment by wigcheng** [comment]
Looks rootfs partition has no problems, empty boot partition is the root cause, very strange.
Please make sure you compile success in u-boot and kernel, please do this steps manually:
1. check <source>/output/u-boot/u-boot-tn-imx/SPL is existing or not
2. check <source>/output/u-boot/u-boot-tn-imx/u-boot.img is existing or not
3. check <source>/output/kernel/arch/arm/boot/zImage is existing or not
4. check <source>/output/kernel/arch/arm/boot/dts/imx7d-pico-pi-qca.dtb is existing or not

If all existed, you can copy those files to boot partitions using ums:
$ sudo cp <source>/output/u-boot/u-boot-tn-imx/u-boot.img mnt/
$ sudo cp <source>/output/kernel/arch/arm/boot/zImage mnt/
$ sudo cp <source>/output/kernel/arch/arm/boot/dts/imx7d-pico-pi-qca.dtb mnt/

SPL need use dd way as follows:
$ sudo dd if=<source>/output/u-boot/u-boot-tn-imx/SPL of=/dev/sdx bs=1k seek=1 conv=sync

Then try again, should be boot successfully!

But that should be auto generated at compiling time, make sure you install all require packages, or try clean build again.
Thanks

**Comment by yunushkin88** [comment]
Sorry, maybe I'm writing in the wrong topic at all. I have a question and how in general now to build/write for example Ubuntu image on the debug board for example Pico I.MX 7 Pico pro maker kit with Android things? Previously, there were ready-made images on the TechNexion website, but now you try to assemble them according to the instructions. Maybe there are still these images and documentation in .pdf somewhere. Or some working complete (step-by-step) instruction explaining how to make an image. Write it down. On the Ubuntu 20.04 virtual machine (Windows 10 host), I build this instruction https://developer.technexion.com/mediawiki/Building-from-source-ubuntu-vm and this instruction 
https://github.com/TechNexion-customization/ubuntu-tn-imx/blob/master/README-imx6.md#imx6imx7-platforms-for-ubuntu-2004-with-x11-framework
the same error appears both when building for example u-boot and when building the main ubuntu image:

*** Configuration file ".config" not found!
***
*** Please run some configurator (e.g. "make oldconfig" or
*** "make menuconfig" or "make xconfig").
***
make[2]: *** [scripts/kconfig/Makefile:48: silentoldconfig] Ошибка 1
make[1]: *** [Makefile:479: silentoldconfig] Ошибка 2
make: *** Нет правила для сборки цели «include/config/auto.conf», требуемой для «include/config/uboot.release».  Останов.

In general, I'm not a linux expert. I would appreciate your help.

**Comment by DalitsoOttorino** [comment]
Hello @yunushkin88,

I am not an expert in linux  as well. I think the issue is due to you're not using their virtual machine. The config files are contained in the virtual machine, so you have to use their virtual machine in order to run some of those commands.

You can download their virtual machine here:
ftp://download.technexion.net/development_resources/development_tools/vm/ 
*I'm using Build_Env_Ubuntu_x64_20.04-20201030.zip

**Comment by DalitsoOttorino** [comment]
Hi @wigcheng,

I suspect I encountered error during compilation, so I tried to remove ubuntu-tn-imx folder, git clone it again and build again.

I noticed when I was building rootfs, I'm faced the same error, there are 4 modules that can't be installed: udisks2, gvfs-daemons, gvfs-backends, gvfs:armhf. However, the build process does not stuck here.

<details>
<summary>snipet of make rootfs</summary>

```
...
aspell-autobuildhash: processing: en [en_US-wo_accents-only].
Processing triggers for rygel (0.38.3-1ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Processing triggers for sgml-base (1.29.1) ...
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 gvfs:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'gnome-terminal' is not installed, so not removed
Package 'xscreensaver' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Setting up udisks2 (2.8.4-1ubuntu1) ...
Failed to scan devices: No such file or directory
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package gvfs-daemons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-backends:
 gvfs-backends depends on gvfs-daemons (= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs-backends (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs:armhf:
 gvfs:armhf depends on gvfs-daemons (<< 1.44.1-1ubuntu1.1~); however:
  Package gvfs-daemons is not configured yet.
 gvfs:armhf depends on gvfs-daemons (>= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs:armhf (--configure):
 dependency problems - leaving unconfigured
dmesg: read kernel buffer failed: Invalid argument
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 gvfs:armhf
/bin/df: cannot read table of mounted file systems: No such file or directory
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because MaxReports is reached already
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Setting up udisks2 (2.8.4-1ubuntu1) ...
Failed to scan devices: No such file or directory
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package gvfs-daemons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-backends:
 gvfs-backends depends on gvfs-daemons (= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs-backends (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs:armhf:
 gvfs:armhf depends on gvfs-daemons (<< 1.44.1-1ubuntu1.1~); however:
  Package gvfs-daemons is not configured yet.
 gvfs:armhf depends on gvfs-daemons (>= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs:armhf (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 gvfs:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)
/usr/bin/touch: cannot touch '/home/ubuntu/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml': No such file or directory
/usr/bin/chown: cannot access '/home/ubuntu/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml': No such file or directory
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
Need to get 0 B/1628 kB of archives.
After this operation, 0 B of additional disk space will be used.
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
(Reading database ... 79226 files and directories currently installed.)
Preparing to unpack .../network-manager_1.22.10-1ubuntu1_armhf.deb ...
Unpacking network-manager (1.22.10-1ubuntu1) over (1.22.10-1ubuntu1) ...
Setting up udisks2 (2.8.4-1ubuntu1) ...
Failed to scan devices: No such file or directory
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
Setting up network-manager (1.22.10-1ubuntu1) ...
invoke-rc.d: could not determine current runlevel
 * Reloading system message bus config...                                                                                                                                                
Failed to open connection to "system" message bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
invoke-rc.d: initscript dbus, action "force-reload" failed.
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package gvfs-daemons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-backends:
 gvfs-backends depends on gvfs-daemons (= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs-backends (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
dpkg: dependency problems prevent configuration of gvfs:armhf:
 gvfs:armhf depends on gvfs-daemons (<< 1.44.1-1ubuntu1.1~); however:
  Package gvfs-daemons is not configured yet.
 gvfs:armhf depends on gvfs-daemons (>= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs:armhf (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.1) ...
Processing triggers for systemd (245.4-4ubuntu3) ...
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 gvfs:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)
Unknown host QEMU_IFLA type: 54
Unknown host QEMU_IFLA type: 54
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Unknown host QEMU_IFLA type: 54
Unknown host QEMU_IFLA type: 54
/usr/bin/chmod: cannot access '/usr/bin/system_init': No such file or directory
\e[1;32mAdd swap partition...Default size is one-fourth of total memory\e[m
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  zram-config
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
Need to get 4312 B of archives.
After this operation, 55.3 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf zram-config all 0.5 [4312 B]
Fetched 4312 B in 1s (3388 B/s)       
E: Can not write log (Is /dev/pts mounted?) - posix_openpt (19: No such device)
Selecting previously unselected package zram-config.
(Reading database ... 79226 files and directories currently installed.)
Preparing to unpack .../zram-config_0.5_all.deb ...
Unpacking zram-config (0.5) ...
Setting up udisks2 (2.8.4-1ubuntu1) ...
Failed to scan devices: No such file or directory
dpkg: error processing package udisks2 (--configure):
 installed udisks2 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of gvfs-daemons:
 gvfs-daemons depends on udisks2; however:
  Package udisks2 is not configured yet.

dpkg: error processing package gvfs-daemons (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of gvfs-backends:
 gvfs-backends depends on gvfs-daemons (= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs-backends (--configure):
 dependency problems - leaving unconfigured
Setting up zram-config (0.5) ...
No apport report written because the error message indicates its a followup error from a previous failure.
No apport report written because the error message indicates its a followup error from a previous failure.
Created symlink /etc/systemd/system/multi-user.target.wants/zram-config.service -> /lib/systemd/system/zram-config.service.
dpkg: dependency problems prevent configuration of gvfs:armhf:
 gvfs:armhf depends on gvfs-daemons (<< 1.44.1-1ubuntu1.1~); however:
  Package gvfs-daemons is not configured yet.
 gvfs:armhf depends on gvfs-daemons (>= 1.44.1-1ubuntu1); however:
  Package gvfs-daemons is not configured yet.

dpkg: error processing package gvfs:armhf (--configure):
 dependency problems - leaving unconfigured
No apport report written because MaxReports is reached already
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 gvfs:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  liballegro4.4 libc-dev-bin libc6-dev libcrypt-dev libdevil1c2 libgavl1 libglu1-mesa libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblcms2-dev liblzma-dev libmng2
  libsdl1.2debian libtiff-dev libtiffxx5 linux-libc-dev manpages manpages-dev zlib1g-dev
Suggested packages:
  glibc-doc libfmt-doc liblzma-doc
The following NEW packages will be installed:
  frei0r-plugins liballegro4.4 libc-dev-bin libc6-dev libcroco3 libcrypt-dev libdevil-dev libdevil1c2 libfmt-dev libgavl1 libglu1-mesa libjbig-dev libjpeg-dev libjpeg-turbo8-dev
  libjpeg62 libjpeg8-dev liblcms2-dev liblzma-dev libmng2 libsdl1.2debian libtiff-dev libtiffxx5 linux-libc-dev manpages manpages-dev zlib1g-dev
0 upgraded, 26 newly installed, 0 to remove and 0 not upgraded.
4 not fully installed or removed.
Need to get 21.2 MB of archives.
After this operation, 48.8 MB of additional disk space will be used.
Get:1 http://ports.ubuntu.com/ubuntu-ports focal/main armhf manpages all 5.05-1 [1314 kB]
Get:2 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf libgavl1 armhf 1.4.0-5 [2781 kB]
Get:3 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf frei0r-plugins armhf 1.7.0-1build1 [324 kB]
Get:4 http://ports.ubuntu.com/ubuntu-ports focal/universe armhf liballegro4.4 armhf 2:4.4.3.1-1 [298 kB]
...
```

</details>

I also noticed when building rootfs, it is using imx6-focol-proprietary.tar.gz, which is strange as I'm building for imx7d, do they share the same rootfs?

After clean build, flashing to the board shows different result, my boot partition is no longer empty:
![Screenshot from 2021-02-22 10-05-20](https://user-images.githubusercontent.com/46814845/108662862-3557c780-750a-11eb-9c0a-0b60350429e7.png)
![Screenshot from 2021-02-22 10-05-52](https://user-images.githubusercontent.com/46814845/108662889-44d71080-750a-11eb-9730-b1032c923f56.png)

After changing to emmc boot mode, it booted up successfully. Wifi and bluetooth is tested to be working. Camera is not working, and audio has not been tested.

**Comment by wigcheng** [comment]
Congratulations, it works!

1. udisks2, gvfs-daemons, gvfs-backends, gvfs:armhf. 
It's normal error message because qemu has no this physical node, it will auto running again when first boot.
2. Yes, Ubuntu 20.04 with kernel 5.4.70 does not support OV5645 camera at this moment, you can use UVC camera first.
3. IMX7 series also adapt the same rootfs-overlay tar file as IMX6 series.

Please close this ticket if you already solve flash image issue, thanks a lot!

**Comment by DalitsoOttorino** [comment]
Thanks Wigcheng,

I appreciate your help a lot thus far!

**Comment by yunushkin88** [comment]
> Hello @yunushkin88,
> 
> I am not an expert in linux as well. I think the issue is due to you're not using their virtual machine. The config files are contained in the virtual machine, so you have to use their virtual machine in order to run some of those commands.
> 
> You can download their virtual machine here:
> ftp://download.technexion.net/development_resources/development_tools/vm/
> *I'm using Build_Env_Ubuntu_x64_20.04-20201030.zip

Thank you very much. Ubuntu has started. Sorry, maybe you have encountered this, I used otg installer since I do not have an sd card on the debugging kit and when I installed the drivers (in Windows 10) so that emmc was seen as a flash drive for installing the image I got about ~8 new usb devices not marked up and not formatted I managed to collect two partitions of ~3.2 and 1.2 GB and I can not combine them in Windows. Next, I formatted these disks with the standard settings FAT 32 and put them using Win32DiskImager on a larger ubuntu disk, it starts, but the question is whether I did everything correctly?)
And is it now possible to run a wi-fi and bluetooth camera in ubuntu?

**Comment by wigcheng** [comment]
@yunushkin88 

Congratulations you made it works as well!

About your concern, I suggest you can download our official demo image as following link, then compare demo image and your compiled image, it's faster to look for difference.

ftp://ftp.technexion.com/demo_software/PICO/IMX7/pico-imx7-emmc/DiskImage/pico-imx7d_pi_ubuntu-20.04-xfce_QCA9377_5-lcd-800x480_20210203.zip

In our Ubuntu 20.04 BSP, both works for WiFi and Bluetooth, if your compiled image don't work, please make sure you put your WiFi/Bluetooth firmware files in rootfs_overlay folder already. In addition, OV5645 Camera does not support at this moment, hope you understand.

Thanks!

**Comment by yunushkin88** [comment]
> @yunushkin88
> 
> Congratulations you made it works as well!
> 
> About your concern, I suggest you can download our official demo image as following link, then compare demo image and your compiled image, it's faster to look for difference.
> 
> ftp://ftp.technexion.com/demo_software/PICO/IMX7/pico-imx7-emmc/DiskImage/pico-imx7d_pi_ubuntu-20.04-xfce_QCA9377_5-lcd-800x480_20210203.zip
> 
> In our Ubuntu 20.04 BSP, both works for WiFi and Bluetooth, if your compiled image don't work, please make sure you put your WiFi/Bluetooth firmware files in rootfs_overlay folder already. In addition, OV5645 Camera does not support at this moment, hope you understand.
> 
> Thanks!

Sorry, but can you tell me, and in previous versions of ubuntu or yocto there was support for the camera? Maybe you have a guide to running the camera on the new ubuntu, thank you!!!

**Comment by wigcheng** [comment]
Please adapt earlier Yocto 2.5 release images as follows link if you insist use OV5645 camera:
ftp://ftp.technexion.com/demo_software/PICO/IMX7/pico-imx7-emmc/DiskImage/pico-imx7_pico-pi_yocto-2.5-qt5_qca9377_lcd-800x480_20210217.zip
