### ISSUE TITLE
File transfer and duplicate device

### ISSUE THREAD

**Issue by DalitsoOttorino** [TechNexion-customization/ubuntu-tn-imx#4]
Hello,

I need your help on the methods to transfer file to my pico-pi-imx7d during runtime. I'm running an ubuntu 20.04 LTS host. Currently, I transfer file by stopping uboot from booting and using "ums 0 mmc 0" to mount as a mass media device, then transfer the file manual and finally boot to the system. I would like to know what other methods can I used to transfer file from my ubuntu host.

Another question I would like to ask is how do you duplicate the device image onto another device? Is it possible to create an image based on the the device I'm currently working on and flash onto another device? If so, what tools would you recommend?

Thanks.

**Comment by wigcheng** [comment]
Hello @DalitsoOttorino 

ANS 1:
If you already compiled a runtime image using our source code, you also can adapt UUU tool to flash image, remember switch boot mode to serial download mode, do you know how to change jumpers?


ANS 2:
You means you want to create a custom image from your eMMC of target device? A lazy way is use "dd" command to copy raw data from /dev/sdx to an output.img on your host PC. But I suggest you can add your changes to this ubuntu source code on your local site, it's easy to record what you modified!

Thanks

**Comment by DalitsoOttorino** [comment]
Thanks Wigcheng,

For question 1:
I'm trying to transfer small file like python code, test data in csv. Right now, I'm trying out ssh and scp to transfer those files.

For question 2:
I like the idea of changing the ubuntu source code itself but I'm not sure how to do it. So far what I've done to the device is install a bunch of python packages. Installing those packages on a fresh new device will take a long time. "dd" command will work but is that the correct way to do it?

I have another question for you:
What can I do if i changed the ubuntu default password and forget what's the new password?

**Comment by wigcheng** [comment]
About question 1:
So you just want to copy your custom files to ubuntu, not copy ubuntu image, right?
scp is a good way to copy file to ubuntu rootfs, you also can try 'rsync', most likely scp without encryption, so it's faster.


About question 2:
You can trying to add your custom files to rootfs_overlay folder before compiling, and if you want to add new packages to default ubuntu image, you can add your target packages name to qemu_install.sh.

About password issue, googling have much answers but I suggest you can remove ubuntu user using root user permission, and re-generate a new ubuntu user with correct password.
