### ISSUE TITLE
Replace havged with rng-tools

### ISSUE THREAD

**Issue by sanje2v** [TechNexion-customization/ubuntu-tn-imx#5]
Using the latest 21 May 2021 fresh Ubuntu 20.04 image on my IMX8MQ-PICO, systemd reports that the service 'haveged' failed to start due to some incompatibility with ARM64. Due to this, the hardware based entropy reported by 'cat /proc/sys/kernel/random/entropy_avail' is around 1000. This might affect predictability of random numbers generation in code and hence in turn affect security and machine learning applications.

I replaced 'haveged' with 'rng-tools' and now the reported entropy has increased to > 3000 like in my desktop PC.

I think the build script should replace the above package in the next iteration.

**Comment by wigcheng** [comment]
Good point! I'll try later and update to my package list if no problems, thanks for your comments.

**Comment by richard-hu** [comment]
Thanks for the feedback. 
Because most i.mx SOCs are equipped with CAAM module, “rng-tools” should fill the kernel entropy for /dev/random from /dev/hwrng(HW random number generator) .
It looks "haveged" doesn't utilize "/dev/hwrng".
we should replace it with "rng-tools".

Thanks~!!!
