### ISSUE TITLE
gen_rootfs.sh ftp server for proprietary package error404

### ISSUE THREAD

**Issue by raspberrypi66** [TechNexion-customization/ubuntu-tn-imx#6]
Change from

https://download.technexion.com/development_resources/NXP/ubuntu/proprietary

to

https://download.technexion.com/development_resources/NXP/ubuntu/20.04/proprietary-package/

I use PICO imx8mp on EGM-G

when I leave error appear system boot without weston
and then if I change  url  to corrent path system can't boot with error Kernel panic - not syncing; No working init found

**Comment by wigcheng** [comment]
Thanks for your feedback.

Yes, proprietary package link just updated, please git pull and test it again.
