### ISSUE TITLE
TEK3-IMX6 support

### ISSUE THREAD

**Issue by abougouffa** [TechNexion-customization/ubuntu-tn-imx#7]
Hello,

I'm trying to build Ubuntu image for the [TEK3-IMX6](https://www.technexion.com/products/embedded-computing/fanless-computing/tek3-series/tek3-imx6) embedded computer, however, the product is not listed on the *Supported Hardware* table.

How can I build a 20.04 version for TEK3-IMX6?, the only image installable on the embedded computer is Ubuntu 16.04, which is quite old.

**Comment by wigcheng** [comment]
Thanks for letting me know someone is using TEK3-IMX6 with Ubuntu OS.
Actually I have no plan for TEK-IMX6 first, but I'll add it to Ubuntu 20.04 because you need it,maybe need one to two weeks, I'm super busy recently :( 

If you're urgent, I suggest you can download our u-boot 2020.04 and kernel 5.4 repo and compile them, and compile this Ubuntu using "pico-imx6", replace u-boot and kernel images manually, should be works.

**Comment by abougouffa** [comment]
Hello @wigcheng ,

Thank you for your quick reply, 

In fact, it is quite urgent, so I would like to compile it, but I can't find the u-boot 2020.04 which supports TEK3-IMX6, in the [`u-boot-tn-imx/board`](https://github.com/TechNexion/u-boot-tn-imx/tree/tn-imx_v2020.04_5.4.70_2.3.0-stable/board/technexion) directory, there is no `tek-imx6`!

Also, I didn't find the documentation of how to compile it! could you suggest some resources for that?

**Comment by wigcheng** [comment]
About u-boot, please use latest tn-imx_v2020.04_5.4.70_2.3.0-next branch, it does support tek-imx6.
I think should be no problems if you know how to cross-compile.

I'll take a look next week if I have time, and add tek3-imx6 to ubuntu 20.04.

**Comment by abougouffa** [comment]
Thank you for the clarification @wigcheng, I really appreciate it!

**Comment by wigcheng** [comment]
@abougouffa I added tek3-imx6 to ubuntu 20.04 already, you can download it and issue command to compile the ubuntu.img runtime image:

make all PLATFORM="tek3-imx6"


Let me know it you can boot up success (It works here, and note that this platform does not validate yet.)
Thanks

**Comment by wigcheng** [comment]
Any update?

**Comment by letis33** [comment]
Hi @wigcheng,

It works like a charm on my TEK3-IMX6 system !

**ubuntu@technexion:~$ lsb_release -a**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04 LTS
Release:	20.04
Codename:	focal

**ubuntu@technexion:~$ uname -a**
Linux technexion 5.4.70 #1 SMP PREEMPT Tue Sep 21 22:02:54 CEST 2021 armv7l armv7l armv7l GNU/Linux

Thanks

**Comment by abougouffa** [comment]
Hello @wigcheng ,

I didn't have the time to try. To respond to an urgent demo, we used the old preinstalled Ubuntu 16.04 and updated it to 20.04.
I will let you know when I give it a try,

Thank you very much for your reactiveness, I really appreciate it.

**Comment by wigcheng** [comment]
Got it, I think should be no problem because @letis33 works using same way.
I'll close this issue first, you can create another ticket if you got issues, thanks!
